# 暂时不写配置
zuul:
  routes:
    project-user: /project/**
    project-config: /config/**
   #设置所有服务都可传递cookie
  ignore-security-headers: true
      #排除某些路由
#    ignored-patterns:
#    - /**/product/listForOrder
#由于本地测试服务启动过多  响应时间过长  设置ribbon超时时间  确保测试通过
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  redis:
    port: 6379
    host: 127.0.0.1
